version: '3'
services:
  postgres:
    image: postgres:12.1
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api/config:/app/config
      - ./api/src:/app/src
      - ./api/test:/app/test
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"