version: '3'
services:
  postgres:
    container_name: database
    image: postgres:12.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api/config:/app/config
      - ./api/src:/app/src
      - ./api/test:/app/test
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client/public:/app/public
      - ./client/src:/app/src
    ports:
      - "3000:3000"